version: "3.7"
services:
  postgres:
    image: postgres:10.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=kong
      - POSTGRES_USER=kong
    healthcheck:
      test: ["CMD", "pg_isready"]
      start_period: 3s
      timeout: 5s
      retries: 3
  
  migrator:
    build: .
    image: rucciva/kong:2.5.1-alpine
    restart: on-failure
    depends_on: 
      postgres:
        condition: service_healthy
    environment:
      - KONG_PG_HOST=postgres
      - KONG_PG_DATABASE=kong
      - KONG_PLUGINS=bundled,oauth2-audience
    entrypoint: sh -c
    command: 
      - kong migrations bootstrap && kong migrations up

  kong:
    build: .
    image: rucciva/kong:2.5.1-alpine
    restart: unless-stopped
    depends_on: 
      migrator:
        condition: service_started
    environment:
      - KONG_PLUGINS=bundled,oauth2-audience
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgres
      - KONG_PG_DATABASE=kong
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_TRUSTED_IPS=0.0.0.0/0,::/0
    ports:
      - 8000:8000
      - 8001:8001
      - 8443:8443
      - 8444:8444